version: '3.1'

networks:
  my-network:
    external: true

services:
  
  messagedb:
    image: postgres
    restart: always
    expose:
    - '5434'
    ports:
      - '5434:5434'
    environment:
      - POSTGRES_USER=usuario
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=messagesdatabase
    command: -p 5434
    networks:
      - my-network

  messageapi:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      - messagedb
    volumes:
      - ./src:/app/src
    networks:
      - my-network